# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  spaName: sample-app
  poolImage: 'ubuntu-latest'

stages: 
- stage: build
  displayName: "Build"
  jobs: 
  - job: build_mvc
    displayName: "Build MVC"
    pool: 
      vmImage: $(poolImage)
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
      workingDirectory: ./mvc
  - job: build_spa
    displayName: "Build SPA"
    pool: 
      vmImage: $(poolImage)
    steps:
    - script: npm run build
      displayName: 'npm run build'
      workingDirectory: ./spa/$(spaName)
# - stage: deploy
#   displayName: "Deploy"
#   dependsOn: build
#   jobs: []