# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  spaName: sample-spa
  poolImage: 'ubuntu-latest'

stages: 
- stage: build
  displayName: "Build"
  jobs: 
  - job: build_mvc
    displayName: "Build MVC"
    pool: 
      vmImage: $(poolImage)
    steps:
    - script: dotnet build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/mvc
      displayName: 'dotnet build $(buildConfiguration)'
      workingDirectory: ./mvc
  - job: build_spa
    displayName: "Build SPA"
    pool: 
      vmImage: $(poolImage)
    steps:
    - script: |
        npm install
        npm run build
        cp /build/ $(Build.ArtifactStagingDirectory)/spa
      displayName: 'npm run build'
      workingDirectory: ./spa/$(spaName)
  - job: publish_artifacts
    dependsOn: 
    - build_mvc
    - build_spa
    displayName: "Publish Artifacts"
    pool: 
      vmImage: $(poolImage)
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
# - stage: deploy
#   displayName: "Deploy"
#   dependsOn: build
#   jobs: []