# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  spaName: sample-spa
  poolImage: 'ubuntu-latest'

stages: 
- stage: build
  displayName: "Build"
  jobs: 
  - job: build_mvc
    displayName: "Build MVC"
    pool: 
      vmImage: $(poolImage)
    steps:
    - script: dotnet build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/mvc
      displayName: 'dotnet build $(buildConfiguration)'
      workingDirectory: ./mvc
    - script: |
        echo "installing NPM packages and building"
        npm install
        npm run build

        cd build 
        echo "creating the spa folder on artifacts staging directory"
        mkdir -p $(Build.ArtifactStagingDirectory)/spa
        echo "copying files to artifacts staging directory"
        cp -vR * $(Build.ArtifactStagingDirectory)/spa
      displayName: 'npm run build'
      workingDirectory: ./spa/$(spaName)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
# - stage: deploy
#   displayName: "Deploy"
#   dependsOn: build
#   jobs: []